## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

Criando o Dataframe inical do Vestibular:

In [5]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'assunto': ['Matematica', 'Portugues', 'Geografia', 'Ingles', 'Historia', 'Fisica', 'Quimica'], \
                  'numero de questoes': [24, 18, 8, 8, 8, 12, 12 ]})
df

      assunto  numero de questoes
0  Matematica                  24
1   Portugues                  18
2   Geografia                   8
3      Ingles                   8
4    Historia                   8
5      Fisica                  12
6     Quimica                  12

In [6]:


np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [7]:
# 1) Seu código aqui
# Porcentagem por assunto:

mat = (df_mat['Qt_acertos'] / df.iloc[0, 1]) * 100
por = (df_por['Qt_acertos'] / df.iloc[1, 1]) * 100
geo = (df_geo['Qt_acertos'] / df.iloc[2, 1]) * 100
ing = (df_ing['Qt_acertos'] / df.iloc[3, 1]) * 100
his = (df_his['Qt_acertos'] / df.iloc[4, 1]) * 100
fis = (df_fis['Qt_acertos'] / df.iloc[5, 1]) * 100
qui = (df_qui['Qt_acertos'] / df.iloc[6, 1]) * 100

In [8]:
# 2) Seu código aqui
# Acertos de cada aluno:
acertos_aluno = df_fis + df_geo + df_his + df_ing + df_mat + df_por + df_qui
acertos_aluno

    Qt_acertos
0           35
1           48
2           50
3           32
4           30
..         ...
95          34
96          27
97          40
98          40
99          42

[100 rows x 1 columns]

In [9]:
# 3) Seu código aqui
# Percentual de cada aluno:
acertos_aluno['Percent_Total'] = (acertos_aluno['Qt_acertos'] / df["numero de questoes"].sum()) * 100
acertos_aluno

    Qt_acertos  Percent_Total
0           35      38.888889
1           48      53.333333
2           50      55.555556
3           32      35.555556
4           30      33.333333
..         ...            ...
95          34      37.777778
96          27      30.000000
97          40      44.444444
98          40      44.444444
99          42      46.666667

[100 rows x 2 columns]

In [10]:
# 4) Seu código aqui
# Contando quantos alunos tiveram 45 pontos ou mais:
corte = acertos_aluno['Qt_acertos'] >= 45
pre_aprovados = corte.sum()
pre_aprovados

34

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [11]:
# seu código aqui
# Alunos desqualificados pelo critério de zeramento: 
criterio = (df_mat['Qt_acertos'] == 0) | (df_fis["Qt_acertos"] == 0) | (df_qui['Qt_acertos'] == 0)
df_reprovados = pd.DataFrame({'Reprovados': criterio})
df_reprovados = df_reprovados[df_reprovados['Reprovados']]
df_reprovados

    Reprovados
3         True
6         True
10        True
12        True
14        True
20        True
25        True
26        True
27        True
33        True
35        True
49        True
56        True
65        True
66        True
72        True
73        True
74        True
84        True
89        True
92        True
94        True
98        True

In [12]:
# Contagem de reprovados:
df_reprovados.sum()

Reprovados    23
dtype: int64

In [13]:
# Média desses alunos em História e Geografia:
df_reprovados['Media_his_geo'] = (df_geo.loc[df_reprovados.index] + df_his.loc[df_reprovados.index]).mean(axis=1)
df_reprovados

    Reprovados  Media_his_geo
3         True            3.0
6         True           12.0
10        True            4.0
12        True            4.0
14        True            2.0
20        True           12.0
25        True            7.0
26        True           13.0
27        True            8.0
33        True            6.0
35        True            9.0
49        True            2.0
56        True           13.0
65        True            5.0
66        True            6.0
72        True           10.0
73        True            5.0
74        True            5.0
84        True            1.0
89        True           13.0
92        True            2.0
94        True            3.0
98        True            8.0

In [14]:
# Aprovados para a segunda fase:
aprovados = criterio[corte]
aprovados = aprovados[aprovados].index
pd.DataFrame({'Aprovados': aprovados})

# Somente 5 alunos atendem aos dois critérios

   Aprovados
0         20
1         27
2         35
3         72
4         89

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [15]:

df_sus = pd.read_csv('https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-f01336d5-5504-4b98-94e0-9d5aba96f91a.c000.csv', sep=';')
df_sus.head(5)

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,0136034c-5d08-454d-bcf7-f2640c9900af-i0b0,f74a177a923f4882fabd3fc25029b2804fa5316d8f47e5...,41,1980-07-22,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FP8073,PFIZER,28290,2022-03-29,Reforço,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
1,28bcb231-f9b8-4315-9da2-17748d548d69-i0b0,0460d42f66dd82c825664fd3ca34c62fa0adf1f54fa4ec...,30,1991-04-05,M,3,PARDA,120035.0,10.0,MARECHAL THAUMATURGO,...,6.0,Povos e Comunidades Tradicionais,210416,SINOVAC/BUTANTAN,Organization/152,2022-02-06,2ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
2,7c0e200d-2e96-4c6e-9a8e-d3c4a24a577f-i0b0,bd752fe1fb6512068a7e427506b259bea1d7418b516a6a...,55,1965-12-03,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,215VCD120W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-06-15,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
3,28e42d7e-bc1a-4628-9485-e3d610e25f35-i0b0,d8d6be00190f654367b2642b0fd147d023e40df8d1089a...,8,2014-04-12,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,NaN,NaN,B202106081,SINOVAC,29501,2022-06-27,1ª Dose,98,COVID-19 SINOVAC - CORONAVAC,Novo PNI
4,c35b981b-afe0-4600-b2bb-66ccac2e4bb3-i0b0,3408e159c4899f96b9808ebe78e56b73bca22b230733e0...,34,1986-10-17,M,99,SEM INFORMACAO,120040.0,10.0,RIO BRANCO,...,16.0,Trabalhadores Industriais,217VCD233W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-09-04,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI

In [17]:
# 1) Sua solução aqui
# Quantidade de registros:
df_sus.shape[0]

384920

In [18]:
# 2) Quantidade de vacinados:
df_sus['paciente_id'].nunique()

314987

In [19]:
# 3) Quantidade de pacientes que tomaram a primeira dose: 
primeira_dose = df_sus['vacina_descricao_dose'].unique()[0]
df_sus['paciente_id'].loc[df_sus['vacina_descricao_dose'] == primeira_dose].nunique()

72006

In [20]:
# 3) solução alternativa
primeira_dose = df_sus['vacina_descricao_dose'].unique()[0]
df_primeira_dose = df_sus[df_sus['vacina_descricao_dose'] == primeira_dose]
df_primeira_dose['paciente_id'].nunique()

72006

In [21]:
# 4) Menores de 18 anos vacinados:
df_menores = df_sus[df_sus['paciente_idade'] < 18]
df_menores['paciente_id'].nunique()

67143

In [22]:
# 5) Quantidade de estabelecimentos que aplicaram a vacina:
df_sus['estabelecimento_razaoSocial'].nunique()

61

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [27]:
# 1) Vacinas aplicadas a menores de 18 anos:
df_menores = df_sus[df_sus['paciente_idade'] < 18].copy()
df_menores

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
3,28e42d7e-bc1a-4628-9485-e3d610e25f35-i0b0,d8d6be00190f654367b2642b0fd147d023e40df8d1089a...,8,2014-04-12,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,NaN,NaN,B202106081,SINOVAC,29501,2022-06-27,1ª Dose,98,COVID-19 SINOVAC - CORONAVAC,Novo PNI
16,6871f196-1a3a-4cda-b973-9b620e5c9a6a-i0b0,92025867c1bfdead367b87461091ae2f5619383ac10777...,6,2015-06-12,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,NaN,NaN,FP8290,Pendente Identificação,Organization/28290,2022-03-31,2ª Dose,99,COVID-19 PEDIÁTRICA - PFIZER COMIRNATY,Novo PNI
17,29fb8135-a3bb-4b3c-88f6-99b4fe529f52-i0b0,48ce0564d76a491ae41c2f1e13d2bc5cdcf7400912221c...,14,2007-04-16,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FD7221,PFIZER,Organization/00394544000851,2021-08-13,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
20,a8653b73-75a7-4d58-92f6-846f1ab48980-i0b0,58b6681a766949cd392f7df765cc2a16fc9996a0f44f6d...,4,2018-09-17,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,220299,SINOVAC/BUTANTAN,152,2023-01-24,1ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
22,c4fe1c06-9d03-4fb3-9f09-d03ae04172ed-i0b0,b04dc8dc9a414410e7defb82eedd78ffeba9326ffe2a5e...,14,2007-04-05,F,99,SEM INFORMACAO,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FA9096,PFIZER,Organization/00394544000851,2021-08-11,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384891,8a7d37de-45a6-425e-9889-2342f5f71ab7-i0b0,ab18fc16766c4a0ec5fd570ea221950efc1a4a85d90964...,8,2014-01-31,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,NaN,NaN,FN5988,Pendente Identificação,Organization/28290,2022-04-18,2ª Dose,99,COVID-19 PEDIÁTRICA - PFIZER COMIRNATY,Novo PNI
384894,8ac9edc6-e290-42e5-ab8e-6d8ac3fbfd33-i0b0,cd7ba0efcbc82f65dcaacc70dab4dd331bbf62d990b208...,12,2008-12-16,F,4,AMARELA,120050.0,10.0,SENA MADUREIRA,...,2.0,Faixa Etária,FA9096,PFIZER,Organization/00394544000851,2021-08-17,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
384898,8afa7a22-e1e8-4d65-9613-e0480e99a8fc-i0b0,c9239e0b9d0da275f82ee54abe4b4a954c503873f135fd...,7,2016-01-15,F,3,PARDA,120070.0,10.0,XAPURI,...,2.0,Faixa Etária,220301,SINOVAC/BUTANTAN,152,2023-03-20,1ª Dose Revacinação,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
384906,8b9c67db-7e78-4eff-8542-c49816a2597a-i0b0,1c54a16ab2f8e6944b3d5d82624e9b649fb680cb3f910e...,13,2008-02-28,F,4,AMARELA,120017.0,10.0,CAPIXABA,...,2.0,Faixa Etária,28230BD,PFIZER,Organization/00394544000851,2021-08-26,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
384914,8c301eca-0286-4f3b-bfaa-7dfa15263373-i0b0,41aa97d6a9b186cf22ffbcab954fb3f248b8351c46a680...,4,2017-11-26,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,NaN,NaN,210520,SINOVAC/BUTANTAN,29501,2022-07-22,1ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI

In [26]:
# 2) Lista de colunas deste Dataframe:
colunas = df_menores.columns
colunas

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

In [30]:
# 3) Contando o campo vacina_categoria_nome:
df_menores['vacina_categoria_nome'].value_counts()

vacina_categoria_nome
Faixa Etária                                      46438
Povos Indígenas                                    4496
Outros                                             3755
Povos e Comunidades Tradicionais                    811
Trabalhadores de Saúde                              248
Comorbidades                                         56
População Privada de Liberdade                       53
Gestantes                                            42
Pessoas com Deficiência                              11
Pessoas Institucionalizadas                           3
Pessoas de 60 anos ou mais institucionalizadas        1
Puérperas                                             1
Trabalhadores da Educação                             1
Name: count, dtype: int64

In [33]:
# 4) Lista de variáveis:
lista_variáveis = ['estabelecimento_valor', 'estabelecimento_razaoSocial', 'estalecimento_noFantasia', 
                  'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome', 'estabelecimento_uf']
df_lista = df_menores.loc[:, lista_variáveis]
df_lista

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
3,5981891,PREFEITURA MUNICIIPAL DE SENA MADUREIRA,UNIDADE BASICA DE SAUDE MODULO I,120050,SENA MADUREIRA,AC
16,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
17,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
20,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
22,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
...,...,...,...,...,...,...
384891,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
384894,2000873,PREFEITURA MUNICIPAL DE SENA MADUREIRA,UNIDADE BASICA DE SAUDE EDSON SALES,120050,SENA MADUREIRA,AC
384898,2001217,PREFEITURA MUNICIPAL DE XAPURI,UNIDADE SAUDE DA FAMILIA JOSE FADUL,120070,XAPURI,AC
384906,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
384914,5981891,PREFEITURA MUNICIIPAL DE SENA MADUREIRA,UNIDADE BASICA DE SAUDE MODULO I,120050,SENA MADUREIRA,AC

In [35]:
# 5) drp_duplicates
df_lista = df_menores.drop_duplicates()
df_lista.shape

(75846, 32)